apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rekor-japower
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rekor-japower
    app.kubernetes.io/part-of: rekor
  name: rekor-japower
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: rekor-japower
status:
  loadBalancer: {}
